[package]
name = "komga-infrastructure-discovery"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
komga-application = { path = "../../application" }
komga-domain = { path = "../../domain" }
komga-infrastructure-base = { path = "../base" }
komga-infrastructure-media-core = { path = "../media-core" }
komga-infrastructure-search = { path = "../search" }
serde.workspace = true
sqlx.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
komga-infrastructure-test-support = { path = "../test-support" }
