[package]
name = "komga-server"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
axum.workspace = true
axum-extra.workspace = true
base64.workspace = true
bcrypt.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower-sessions.workspace = true
oauth2.workspace = true
tantivy.workspace = true
sqlx.workspace = true
zip.workspace = true
flate2.workspace = true
lopdf.workspace = true
quick-xml.workspace = true
time.workspace = true
futures-util.workspace = true
getrandom.workspace = true
async-trait.workspace = true
image.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
komga-config = { path = "../config" }
komga-domain = { path = "../domain" }
komga-application = { path = "../application" }
komga-infrastructure-identity = { path = "../infrastructure/identity" }
komga-infrastructure-jobs = { path = "../infrastructure/jobs" }
komga-infrastructure-operational = { path = "../infrastructure/operational" }
komga-infrastructure-opds = { path = "../infrastructure/opds" }
komga-infrastructure-tasks = { path = "../infrastructure/tasks" }
komga-infrastructure-media-access = { path = "../infrastructure/media-access" }
komga-infrastructure-media-metadata = { path = "../infrastructure/media-metadata" }
komga-infrastructure-base = { path = "../infrastructure/base" }
komga-infrastructure-discovery = { path = "../infrastructure/discovery" }
komga-infrastructure-media-core = { path = "../infrastructure/media-core" }
komga-infrastructure-search = { path = "../infrastructure/search" }
komga-interfaces = { path = "../interfaces" }
komga-kepubify = { path = "../kepubify" }

[build-dependencies]
komga-build-support = { path = "../build-support" }

[dev-dependencies]
komga-interfaces = { path = "../interfaces", features = ["allow-missing-webui-dist"] }
