pub(crate) const DELETE_LIBRARY_EXCLUSIONS_SQL: &str =
    "DELETE FROM LIBRARY_EXCLUSIONS WHERE LIBRARY_ID = ?";
pub(crate) const DELETE_LIBRARY_USER_SHARING_SQL: &str =
    "DELETE FROM USER_LIBRARY_SHARING WHERE LIBRARY_ID = ?";
pub(crate) const DELETE_LIBRARY_SIDECAR_SQL: &str = "DELETE FROM SIDECAR WHERE LIBRARY_ID = ?";

pub(crate) const DELETE_LIBRARY_COLLECTION_SERIES_SQL: &str = r#"
DELETE FROM COLLECTION_SERIES
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_READ_PROGRESS_SERIES_SQL: &str = r#"
DELETE FROM READ_PROGRESS_SERIES
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_THUMBNAIL_SERIES_SQL: &str = r#"
DELETE FROM THUMBNAIL_SERIES
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_SERIES_ALTERNATE_TITLE_SQL: &str = r#"
DELETE FROM SERIES_METADATA_ALTERNATE_TITLE
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_SERIES_GENRE_SQL: &str = r#"
DELETE FROM SERIES_METADATA_GENRE
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_SERIES_LINK_SQL: &str = r#"
DELETE FROM SERIES_METADATA_LINK
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_SERIES_SHARING_SQL: &str = r#"
DELETE FROM SERIES_METADATA_SHARING
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_SERIES_TAG_SQL: &str = r#"
DELETE FROM SERIES_METADATA_TAG
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_SERIES_METADATA_SQL: &str = r#"
DELETE FROM SERIES_METADATA
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_BOOK_METADATA_AGGREGATION_AUTHOR_SQL: &str = r#"
DELETE FROM BOOK_METADATA_AGGREGATION_AUTHOR
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_BOOK_METADATA_AGGREGATION_TAG_SQL: &str = r#"
DELETE FROM BOOK_METADATA_AGGREGATION_TAG
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_BOOK_METADATA_AGGREGATION_SQL: &str = r#"
DELETE FROM BOOK_METADATA_AGGREGATION
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_READLIST_BOOK_SQL: &str = r#"
DELETE FROM READLIST_BOOK
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_READ_PROGRESS_SQL: &str = r#"
DELETE FROM READ_PROGRESS
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_THUMBNAIL_BOOK_SQL: &str = r#"
DELETE FROM THUMBNAIL_BOOK
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_MEDIA_PAGE_SQL: &str = r#"
DELETE FROM MEDIA_PAGE
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_MEDIA_FILE_SQL: &str = r#"
DELETE FROM MEDIA_FILE
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_MEDIA_SQL: &str = r#"
DELETE FROM MEDIA
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_BOOK_METADATA_AUTHOR_SQL: &str = r#"
DELETE FROM BOOK_METADATA_AUTHOR
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_BOOK_METADATA_LINK_SQL: &str = r#"
DELETE FROM BOOK_METADATA_LINK
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_BOOK_METADATA_TAG_SQL: &str = r#"
DELETE FROM BOOK_METADATA_TAG
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_BOOK_METADATA_SQL: &str = r#"
DELETE FROM BOOK_METADATA
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
)
"#;

pub(crate) const DELETE_LIBRARY_BOOK_SQL: &str = "DELETE FROM BOOK WHERE LIBRARY_ID = ?";
pub(crate) const DELETE_LIBRARY_SERIES_SQL: &str = "DELETE FROM SERIES WHERE LIBRARY_ID = ?";

pub(crate) const DELETE_LIBRARY_DEPENDENCY_SQL: &[&str] = &[
    DELETE_LIBRARY_EXCLUSIONS_SQL,
    DELETE_LIBRARY_USER_SHARING_SQL,
    DELETE_LIBRARY_SIDECAR_SQL,
    DELETE_LIBRARY_COLLECTION_SERIES_SQL,
    DELETE_LIBRARY_READ_PROGRESS_SERIES_SQL,
    DELETE_LIBRARY_THUMBNAIL_SERIES_SQL,
    DELETE_LIBRARY_SERIES_ALTERNATE_TITLE_SQL,
    DELETE_LIBRARY_SERIES_GENRE_SQL,
    DELETE_LIBRARY_SERIES_LINK_SQL,
    DELETE_LIBRARY_SERIES_SHARING_SQL,
    DELETE_LIBRARY_SERIES_TAG_SQL,
    DELETE_LIBRARY_SERIES_METADATA_SQL,
    DELETE_LIBRARY_BOOK_METADATA_AGGREGATION_AUTHOR_SQL,
    DELETE_LIBRARY_BOOK_METADATA_AGGREGATION_TAG_SQL,
    DELETE_LIBRARY_BOOK_METADATA_AGGREGATION_SQL,
    DELETE_LIBRARY_READLIST_BOOK_SQL,
    DELETE_LIBRARY_READ_PROGRESS_SQL,
    DELETE_LIBRARY_THUMBNAIL_BOOK_SQL,
    DELETE_LIBRARY_MEDIA_PAGE_SQL,
    DELETE_LIBRARY_MEDIA_FILE_SQL,
    DELETE_LIBRARY_MEDIA_SQL,
    DELETE_LIBRARY_BOOK_METADATA_AUTHOR_SQL,
    DELETE_LIBRARY_BOOK_METADATA_LINK_SQL,
    DELETE_LIBRARY_BOOK_METADATA_TAG_SQL,
    DELETE_LIBRARY_BOOK_METADATA_SQL,
    DELETE_LIBRARY_BOOK_SQL,
    DELETE_LIBRARY_SERIES_SQL,
];
