pub(crate) const EMPTY_TRASH_BOOK_METADATA_SQL: &str = r#"
DELETE FROM BOOK_METADATA
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_METADATA_AUTHOR_SQL: &str = r#"
DELETE FROM BOOK_METADATA_AUTHOR
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_METADATA_LINK_SQL: &str = r#"
DELETE FROM BOOK_METADATA_LINK
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_METADATA_TAG_SQL: &str = r#"
DELETE FROM BOOK_METADATA_TAG
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_MEDIA_SQL: &str = r#"
DELETE FROM MEDIA
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_MEDIA_FILE_SQL: &str = r#"
DELETE FROM MEDIA_FILE
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_MEDIA_PAGE_SQL: &str = r#"
DELETE FROM MEDIA_PAGE
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_THUMBNAIL_SQL: &str = r#"
DELETE FROM THUMBNAIL_BOOK
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_READ_PROGRESS_SQL: &str = r#"
DELETE FROM READ_PROGRESS
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_READLIST_SQL: &str = r#"
DELETE FROM READLIST_BOOK
WHERE BOOK_ID IN (
  SELECT ID
  FROM BOOK
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_BOOK_DEPENDENCY_SQL: &[&str] = &[
    EMPTY_TRASH_BOOK_METADATA_SQL,
    EMPTY_TRASH_BOOK_METADATA_AUTHOR_SQL,
    EMPTY_TRASH_BOOK_METADATA_LINK_SQL,
    EMPTY_TRASH_BOOK_METADATA_TAG_SQL,
    EMPTY_TRASH_BOOK_MEDIA_SQL,
    EMPTY_TRASH_BOOK_MEDIA_FILE_SQL,
    EMPTY_TRASH_BOOK_MEDIA_PAGE_SQL,
    EMPTY_TRASH_BOOK_THUMBNAIL_SQL,
    EMPTY_TRASH_BOOK_READ_PROGRESS_SQL,
    EMPTY_TRASH_BOOK_READLIST_SQL,
];

pub(crate) const EMPTY_TRASH_SERIES_METADATA_SQL: &str = r#"
DELETE FROM SERIES_METADATA
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_ALTERNATE_TITLE_SQL: &str = r#"
DELETE FROM SERIES_METADATA_ALTERNATE_TITLE
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_GENRE_SQL: &str = r#"
DELETE FROM SERIES_METADATA_GENRE
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_LINK_SQL: &str = r#"
DELETE FROM SERIES_METADATA_LINK
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_SHARING_SQL: &str = r#"
DELETE FROM SERIES_METADATA_SHARING
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_TAG_SQL: &str = r#"
DELETE FROM SERIES_METADATA_TAG
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_THUMBNAIL_SQL: &str = r#"
DELETE FROM THUMBNAIL_SERIES
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_READ_PROGRESS_SQL: &str = r#"
DELETE FROM READ_PROGRESS_SERIES
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_COLLECTION_SQL: &str = r#"
DELETE FROM COLLECTION_SERIES
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_BOOK_METADATA_AGGREGATION_AUTHOR_SQL: &str = r#"
DELETE FROM BOOK_METADATA_AGGREGATION_AUTHOR
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_BOOK_METADATA_AGGREGATION_TAG_SQL: &str = r#"
DELETE FROM BOOK_METADATA_AGGREGATION_TAG
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_BOOK_METADATA_AGGREGATION_SQL: &str = r#"
DELETE FROM BOOK_METADATA_AGGREGATION
WHERE SERIES_ID IN (
  SELECT ID
  FROM SERIES
  WHERE LIBRARY_ID = ?
    AND DELETED_DATE IS NOT NULL
)
"#;

pub(crate) const EMPTY_TRASH_SERIES_DEPENDENCY_SQL: &[&str] = &[
    EMPTY_TRASH_SERIES_READ_PROGRESS_SQL,
    EMPTY_TRASH_SERIES_COLLECTION_SQL,
    EMPTY_TRASH_SERIES_THUMBNAIL_SQL,
    EMPTY_TRASH_SERIES_METADATA_SQL,
    EMPTY_TRASH_SERIES_ALTERNATE_TITLE_SQL,
    EMPTY_TRASH_SERIES_GENRE_SQL,
    EMPTY_TRASH_SERIES_LINK_SQL,
    EMPTY_TRASH_SERIES_SHARING_SQL,
    EMPTY_TRASH_SERIES_TAG_SQL,
    EMPTY_TRASH_SERIES_BOOK_METADATA_AGGREGATION_AUTHOR_SQL,
    EMPTY_TRASH_SERIES_BOOK_METADATA_AGGREGATION_TAG_SQL,
    EMPTY_TRASH_SERIES_BOOK_METADATA_AGGREGATION_SQL,
];

pub(crate) const DELETE_BOOK_METADATA_SQL: &str = "DELETE FROM BOOK_METADATA WHERE BOOK_ID = ?";
pub(crate) const DELETE_BOOK_METADATA_AUTHOR_SQL: &str =
    "DELETE FROM BOOK_METADATA_AUTHOR WHERE BOOK_ID = ?";
pub(crate) const DELETE_BOOK_METADATA_LINK_SQL: &str =
    "DELETE FROM BOOK_METADATA_LINK WHERE BOOK_ID = ?";
pub(crate) const DELETE_BOOK_METADATA_TAG_SQL: &str =
    "DELETE FROM BOOK_METADATA_TAG WHERE BOOK_ID = ?";
pub(crate) const DELETE_BOOK_MEDIA_SQL: &str = "DELETE FROM MEDIA WHERE BOOK_ID = ?";
pub(crate) const DELETE_BOOK_MEDIA_FILE_SQL: &str = "DELETE FROM MEDIA_FILE WHERE BOOK_ID = ?";
pub(crate) const DELETE_BOOK_MEDIA_PAGE_SQL: &str = "DELETE FROM MEDIA_PAGE WHERE BOOK_ID = ?";
pub(crate) const DELETE_BOOK_THUMBNAIL_SQL: &str = "DELETE FROM THUMBNAIL_BOOK WHERE BOOK_ID = ?";
pub(crate) const DELETE_BOOK_READ_PROGRESS_SQL: &str =
    "DELETE FROM READ_PROGRESS WHERE BOOK_ID = ?";
pub(crate) const DELETE_BOOK_READLIST_SQL: &str = "DELETE FROM READLIST_BOOK WHERE BOOK_ID = ?";

pub(crate) const DELETE_BOOK_DEPENDENCY_SQL: &[&str] = &[
    DELETE_BOOK_METADATA_SQL,
    DELETE_BOOK_METADATA_AUTHOR_SQL,
    DELETE_BOOK_METADATA_LINK_SQL,
    DELETE_BOOK_METADATA_TAG_SQL,
    DELETE_BOOK_MEDIA_SQL,
    DELETE_BOOK_MEDIA_FILE_SQL,
    DELETE_BOOK_MEDIA_PAGE_SQL,
    DELETE_BOOK_THUMBNAIL_SQL,
    DELETE_BOOK_READ_PROGRESS_SQL,
    DELETE_BOOK_READLIST_SQL,
];

pub(crate) const DELETE_SERIES_ALTERNATE_TITLE_SQL: &str =
    "DELETE FROM SERIES_METADATA_ALTERNATE_TITLE WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_GENRE_SQL: &str =
    "DELETE FROM SERIES_METADATA_GENRE WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_LINK_SQL: &str =
    "DELETE FROM SERIES_METADATA_LINK WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_SHARING_SQL: &str =
    "DELETE FROM SERIES_METADATA_SHARING WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_TAG_SQL: &str =
    "DELETE FROM SERIES_METADATA_TAG WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_THUMBNAIL_SQL: &str =
    "DELETE FROM THUMBNAIL_SERIES WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_READ_PROGRESS_SQL: &str =
    "DELETE FROM READ_PROGRESS_SERIES WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_COLLECTION_SQL: &str =
    "DELETE FROM COLLECTION_SERIES WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_METADATA_SQL: &str =
    "DELETE FROM SERIES_METADATA WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_BOOK_METADATA_AGGREGATION_AUTHOR_SQL: &str =
    "DELETE FROM BOOK_METADATA_AGGREGATION_AUTHOR WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_BOOK_METADATA_AGGREGATION_TAG_SQL: &str =
    "DELETE FROM BOOK_METADATA_AGGREGATION_TAG WHERE SERIES_ID = ?";
pub(crate) const DELETE_SERIES_BOOK_METADATA_AGGREGATION_SQL: &str =
    "DELETE FROM BOOK_METADATA_AGGREGATION WHERE SERIES_ID = ?";

pub(crate) const DELETE_SERIES_DEPENDENCY_SQL: &[&str] = &[
    DELETE_SERIES_READ_PROGRESS_SQL,
    DELETE_SERIES_COLLECTION_SQL,
    DELETE_SERIES_THUMBNAIL_SQL,
    DELETE_SERIES_ALTERNATE_TITLE_SQL,
    DELETE_SERIES_GENRE_SQL,
    DELETE_SERIES_LINK_SQL,
    DELETE_SERIES_SHARING_SQL,
    DELETE_SERIES_TAG_SQL,
    DELETE_SERIES_METADATA_SQL,
    DELETE_SERIES_BOOK_METADATA_AGGREGATION_AUTHOR_SQL,
    DELETE_SERIES_BOOK_METADATA_AGGREGATION_TAG_SQL,
    DELETE_SERIES_BOOK_METADATA_AGGREGATION_SQL,
];
