[package]
name = "komga-infrastructure"
version.workspace = true
edition.workspace = true

[features]
image-nasm = ["image/nasm"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bcrypt.workspace = true
komga-domain = { path = "../domain" }
komga-application = { path = "../application" }
komga-infrastructure-base = { path = "base" }
komga-epub = { path = "../epub" }
komga-kepubify = { path = "../kepubify" }
flate2.workspace = true
futures-util.workspace = true
getrandom.workspace = true
image.workspace = true
icu.workspace = true
language-tags.workspace = true
lopdf.workspace = true
pdfium-render.workspace = true
quick-xml.workspace = true
reqwest.workspace = true
regex.workspace = true
rxing.workspace = true
serde.workspace = true
serde_json.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
sha2.workspace = true
sqlx.workspace = true
tantivy.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
unrar.workspace = true
unicode-normalization.workspace = true
url.workspace = true
zip.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[build-dependencies]
komga-build-support = { path = "../build-support" }

[dev-dependencies]
komga-infrastructure-test-support = { path = "test-support" }
