[package]
name = "komga-oauth"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
oauth2.workspace = true
openidconnect.workspace = true
oauth2-reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tokio.workspace = true
