[package]
name = "komga-interfaces"
version.workspace = true
edition.workspace = true
publish = false

[features]
allow-missing-webui-dist = []

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-extra.workspace = true
base64.workspace = true
bcrypt.workspace = true
flate2.workspace = true
http-body.workspace = true
image.workspace = true
icu.workspace = true
komga-domain = { path = "../domain" }
komga-application = { path = "../application" }
komga-kepubify = { path = "../kepubify" }
komga-oauth = { path = "../oauth" }
lopdf.workspace = true
mime_guess.workspace = true
oauth2.workspace = true
quick-xml.workspace = true
reqwest.workspace = true
regex.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower-http.workspace = true
tracing.workspace = true
futures-util.workspace = true
async-trait.workspace = true
zip.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
komga-infrastructure-base = { path = "../infrastructure/base" }
komga-infrastructure-identity = { path = "../infrastructure/identity" }
komga-infrastructure-media-core = { path = "../infrastructure/media-core" }
komga-infrastructure-operational = { path = "../infrastructure/operational" }
sqlx.workspace = true
tower.workspace = true

[build-dependencies]
komga-build-support = { path = "../build-support" }
