CREATE TABLE SERIES_METADATA_CONTRIBUTION (
    BOOK_ID                            TEXT    NOT NULL,
    PROVIDER                           TEXT    NOT NULL,
    SOURCE_FILE_LAST_MODIFIED_SECONDS  INTEGER NOT NULL,
    SOURCE_FILE_SIZE                   INTEGER NOT NULL,
    SOURCE_MEDIA_TYPE                  TEXT    NOT NULL,
    SOURCE_MEDIA_MODIFIED_SECONDS      INTEGER NOT NULL,
    PAYLOAD_FORMAT_VERSION             INTEGER NOT NULL,
    OUTCOME                            TEXT    NOT NULL,
    PAYLOAD                            TEXT    NULL,
    UPDATED_AT                         TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BOOK_ID, PROVIDER),
    CHECK (PROVIDER IN ('COMICINFO', 'EPUB')),
    CHECK (OUTCOME IN ('PRESENT', 'ABSENT')),
    CHECK (
        (OUTCOME = 'PRESENT' AND PAYLOAD IS NOT NULL)
        OR
        (OUTCOME = 'ABSENT' AND PAYLOAD IS NULL)
    )
);
