name: Tests

on:
  pull_request:
    paths-ignore:
      - 'komga-webui/**'
      - 'komga/**'
      - 'komga-tray/**'
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - 'komga-webui/**'
      - 'komga/**'
      - 'komga-tray/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    name: Rust tests - ${{ matrix.os }}
    defaults:
      run:
        working-directory: komga-rust
    steps:
      - uses: actions/checkout@v7
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run cargo nextest
        env:
          CARGO_TERM_COLOR: always
          RUST_BACKTRACE: "1"
        run: cargo nextest run --workspace --no-fail-fast
